okfn-brasil/jarbas

- README.md
Tapioca-jarbas is a python wrapper for the API based in tapioca project, it has support for the three jarbas endpoints and for pagination in the /document/ endpoint.
> Adding tapioca-jarbas referente in Readme file

- jarbas/core/management/commands/receipts.py
- jarbas/core/models.py
- jarbas/core/tests/test_receipts_command.py
- jarbas/core/tests/test_reimbursement_model.py
Takes ages, must be rewrite using lauching multiple `Reimbursement.get_receipt_url()` in parallel…
… but that's what we've got now.
> Add command to fetch receipts

- .gitignore
- gulpfile.js
`npm run watch` compiles at start and doesn't crash when Elms fails to compile.
> Better gulpfile.js for Elm developers

- jarbas/frontend/elm/Documents/Update.elm
The input labels wasn't translating to the browser language. Even in the [official website](http://jarbas.datasciencebr.com/), the sidebar was translating to _Portuguese_ and input labels was in _English_.
> Fixing translation for input labels

- Dockerfile-nginx
- contrib/nginx
- contrib/nginx.docker
**Note**: The `contrib/nginx` was prepared for the future Docker provision/deploy and was outdated with the current settings. I moved it to `contrib/nginx.docker` and kept the current version as `contrib/nginx` (cc @gomex @gwmoura).
> Set nginx to always use HTTPS

- jarbas/core/management/commands/receipts.py
- jarbas/core/models.py
- jarbas/core/tests/test_receipts_command.py
- jarbas/core/tests/test_reimbursement_model.py
- requirements.txt
Multithreading `receipts` command was opening too many db connections. This PR uses bulk update method to speed up the execution and keep the connections to the db sane ; )
> Use bulk update in receipts command

- jarbas/core/management/commands/receipts.py
- jarbas/core/models.py
- jarbas/core/tests/test_receipt_class.py
- jarbas/core/tests/test_receipts_command.py
- jarbas/core/tests/test_reimbursement_model.py
The `receipts` command would break if we get a HTTP error. Not anymore ; )
> Avoid stopping bulk update on HTTP error (receipts command)

- jarbas/api/views.py
- jarbas/core/models.py
- jarbas/core/querysets.py
This PR moves a bunch of logic that was polluting the `views.py` to a proper `QuerySet` object. It also enhance the readability of the now-called `filter_tuple` thing.
> Refactor views moving queries logic to a QuerySet object

- jarbas/core/management/commands/irregularities.py
- jarbas/core/tests/test_irregularities_command.py
Make `python manage.py irregularties <file path>` faster by using bulk updates.
> Refactor irregularities commands using bulk update

- jarbas/core/management/commands/companies.py
This is a really simple change I've made while working on the #124 issue. On the skip list, activity was written wrong, so the API was making a not full formated JSON.
> fixing text. Now the api prints the correct JSON

- docker-compose.yml
This fixies the issue @glauberramos had on #134 
The problem is when you `yarn install` dependencies on your mac, you will build an elm binary for mac, that won't work when shared with docker.
This simple line stops docker from sharing this folder and you will be able to run your own `yarn install` locally if you want.
> Do not share node_modules folder

- Dockerfile-elm
- README.md
- docker-compose.yml
Avoid using `npm install -g yarn` and follow [`yarn` docs](https://yarnpkg.com/docs/install). Maybe relevant for #137 and #129.
> Install yarn the proper way in Docker

- jarbas/frontend/elm/Internationalization.elm
Add human readable layers to `election_expenses` and `invalid_cnpj_cpf` (as in [1748889](https://jarbas.serenatadeamor.org/#/document/1748889)):
`invalid_cnpj_cpf` becomes either _Invalid CNPJ or CPF_ or _CPF ou CNPJ inválidos_. And `election_expenses` becomes either _Expense in electoral campaign_ or _Gasto com campanha eleitoral_.
> Add human label to new classifiers

- README.md
This PR fixes a typo and a link for toolbox that was going to Rosie repo.
> fixes typo and a link in README

- jarbas/core/management/commands/reimbursements.py
- jarbas/core/tests/test_reimbursements_command.py
- requirements.txt
As suggested by @cacarrara in #170:
> Enhance user output when loading reimbursements

- jarbas/core/admin.py
In Django Admin the default history was in use (which shows only changes made via the admin). This PR implements the `django-simple-history` history page showing any kind of change made in the models.
> Fix django-simple-history in admin

- Dockerfile
- README.md
As documentation and Dockerfile target developers, this sounded reasonable.
> Add requeriments-dev.txt to docs & Dockerfile

- jarbas/core/context_processors.py
- jarbas/dashboard/templates/admin/base.html
- jarbas/frontend/views.py
- jarbas/settings.py
Following DRY now Google Analytics is in a context processor, so both the Elm frontend and the dashboard get the value.
> Add Google Analytics to dashboard

- jarbas/dashboard/admin.py
- jarbas/dashboard/static/dashboard.css
- jarbas/dashboard/tests/test_dashboard_admin.py
As suggested in #186 this PR:
* Adds a HTML link to the receipt URL
* Shows subquota descriptions in pt_BR
* Shows suspicions in pt_BR
As highlighted here:
In addition:
* Automatically tries to fetch receipt URL before loading the details page
* Normalizes suquota spelling in pt_BR as _subcota_
* Sort field names alphabetically in detail page
> Enhance reimbursement detail page UI

- jarbas/dashboard/admin.py
Basically a one line commit to allow users to sort results in the dashboard using the _value_ column:
Thanks @luzfcb for the solution. Thanks @vncscoelho for the [bug report](https://twitter.com/vcoelho/status/872495947841982468).
> Allow users to order by value column

- jarbas/dashboard/admin.py
- jarbas/dashboard/tests/test_dashboard_admin.py
In #201 we handled the subquotas filter using an `int` — as Django default is to [highlight filters comparing `str` (not `int`)](https://github.com/django/django/blob/master/django/contrib/admin/filters.py#L109) I changed our logic to store the lookup with `str`. This simple fix enables users to see which subquota they have selected (and we don't have to cast values from the request to `int` anymore):
> Subquota list filter: UI fix

- jarbas/dashboard/admin.py
- jarbas/frontend/elm/Reimbursement/Decoder.elm
Add link to receipt in the Jarbas Dashboard list view - close #250 
Add a column in dashboard with a link (:page_with_curl:) to the receipt image
Open the link at `dashboard/core/reimbursement/`, will have a :page_with_curl: in between "Reembolso" and "Nome do Parlamentar" in some lines. Filter to the reimbursements of 2012 to see the blank column when don't have a receipt image link.
@cuducos or @jtemporal 
**TODO**
> Add link to receipt in the Jarbas Dashboard list view

- jarbas/core/management/commands/suspicions.py
- jarbas/core/tests/test_suspicions_command.py
The hardcoded number of workers on the suspicions command might not run in production (too many Postgres connection at the same time). So parametrized it: you can pass it as an argument, e.g.:
```console
$ python manage.py suspicions /mnt/data/suspicions.xz --workers 4
```
> Parametrizes thread workers in suspicions command

- jarbas/api/views.py
- jarbas/core/querysets.py
- jarbas/core/tests/test_reimbursement_model.py
- jarbas/dashboard/admin.py
Fix the 'no' option for suspicions filter - fix #256  
Add a boolean as param to the suspicions queryset. The boolean is true when the value of the filter is 'yes', so it returns just the suspects and false when the value of the filter is 'no', so this method returns just the reimbursements that are not a supect.
Open dashboard, click on Reimbursements, click on 'no' for the suspicions filter. if it works, the list of reimbursements shouldn't show the suspects reimbursements (Those that the last column is true) .
@cuducos or @jtemporal 
I am not sure about the tests that I wrote, so.. special attention there.
Thank you.
> Fix suspicions filter

- docker-compose.prod.yml
- docker-compose.yml
As suggested in #245, after that PR was merged we'll need to get back to the images from Docker Hub. This is what this PR does ; )
> Bring back Docker images from Docker Hub

- docker-compose.yml
As suggested in #240, after that PR was merged we'll need to get back to the images from Docker Hub. This is what this PR does ; )
> Bring back Docker Hub images

- jarbas/core/querysets.py
- jarbas/core/tests/test_reimbursement_model.py
- jarbas/dashboard/admin.py
In Jarbas Dashboard users could click in the table headers to *try* to sort the results by value, date, etc…
Unfortunately this user selected ordering was being overridden by the search vector rank.
Fortunately this PR fixes this bug ; )
Before calling the `.order_by('-rank')` into the Django QuerySet Jarbas will check if is there any previous ordering in place.
1. Run Jarbas from this branch
2. Access the dashboard (the path is `/dashboard`)
3. Search for some text using  the search bar
4. Try to filter by some clickable column headers — hopefully it'll work ; )
@anaschwendler
> Keep user selected ordering in the dashboard

- README.md
- docker-compose.prod.yml
Change prod docker-compose file to use proxy to handle SSL Offload and auto SSL certificate renewal.
Easy the certificate renewall and related operations
Used jwilder/nginx-proxy and jrcs/letsencrypt-nginx-proxy-companion container images.
```
docker-compose up -d && docker-compose logs -f --tail=10
``` 
Certificate shall be generated on start.
cuducos
**TODO**
> Use SSL Offload and auto certificate renewall

- Dockerfile
- README.md
- docker-compose.prod.yml
This is needed since on production we still need some Django commands such as collectstatic and migrate
Having `gunicorn` as an `entrypoint` for the Django production container makes it difficult to run Django commands such as `python manage.py collectstatic` or `python manage.py migrate`.
Set `gunicorn` as a `command` not as `entrypoint`.
Comment out the `image: …` and add to `docker-compose.yml` on the `django` container:
```yaml
build:
context: .
```
Then `docker-compose -f docker-compose.yml -f docker-compose.prod.yml run django collectstatic --noinput`
> Remove entrypoint from production compose

- .travis.yml
- README.md
- requirements.txt
Make tests run quicker.
Added `--parallel` argument to docs and `.travis.yml` as well as a lib to fix traceback when using this option.
Only only in UNIX based systems (sorry, according to Django `--parallel` argument is [not compatible with Windows](https://docs.djangoproject.com/en/1.11/ref/django-admin/#cmdoption-test-parallel)): Copy and paste the test command from the `README.md` and compare to the time taken without the added argument.
For example:
```console
$ docker-compose run --rm django test && docker-compose run --rm django test  --parallel
```
The first result is what we have today, the second is with multiple tests running in parallel.
**Who can help …
> Use parallel argument in tests

- Dockerfile-elm
The Docker image to render Elm was too big (723MB):
```
$ docker images | grep jarbas
datasciencebr/jarbas-frontend   latest              26f5ad1240ee        12 days ago         723MB
datasciencebr/jarbas-backend    latest              dde71b4b84b6        12 days ago         181MB
```
I suggest we use the `slim` version of the `node` Docker image instead (I tried `alpine` but ended up with some `npm` errors). This reduced the image size in 61%:
```
jarbas_elm_alpine               latest              06f7c4734ab6        2 minutes ago       279MB
```
Edit `docker-compose.yml` to use `Dockerfile-elm` file instead of pulling `datasciencebr/jarbas-frontend`. Build …
> Use slim to reduce Elm container

- docker-compose.override.yml
- docker-compose.prod.yml
- docker-compose.yml
Running PostgreSQL in our Digital Ocean droplets was too consuming, we needed to fix that.
We moved the database to a dedicated service for now.
Access [jarbas.serenata.ai](https://jarbas.serenata.ai) as it is already using this new setup (it was deployed with this branch not `master` after last week crash).
@Irio @anaschwendler @jtemporal (who loves Docker when it works, which seams to be the case)
> Remove PostgreSQL from Docker architecture for production
