okfn-brasil/jarbas

.gitignore
jarbas/core/tests/test_loaddatasets_command.py

Adding more tests and minor add to gitignore file

Django commands tests

---

README.md

Adding info about an error that some macOS users might have.

Changing README 

---

jarbas/frontend/elm/Documents/View.elm
jarbas/frontend/elm/Format/Number.elm
jarbas/frontend/elm/Internationalization.elm
jarbas/frontend/tests/elm-tests/Tests.elm

Format prices in the UI

---

Dockerfile
Dockerfile-elm
Makefile
README.md
contrib/copyassets.sh

Solving problem with migrating data to postgres

---

jarbas/frontend/elm/Documents/Receipt/View.elm
jarbas/frontend/elm/Documents/Supplier/View.elm
jarbas/frontend/elm/Documents/View.elm

Useful for manipulating the DOM.

Give class names to receipt and source links

---

elm-package.json
jarbas/frontend/elm/Documents/View.elm
jarbas/frontend/elm/Internationalization.elm

Cuducos add currency link

---

README.md

Mention settings in Docker instructions

---

elm-package.json
jarbas/frontend/elm/Documents/Company/Decoder.elm
jarbas/frontend/elm/Documents/Company/Model.elm
jarbas/frontend/elm/Documents/Company/View.elm
jarbas/frontend/elm/Documents/View.elm
jarbas/frontend/elm/Format/Date.elm
jarbas/frontend/elm/Format/Date/Config/Config_pt_br.elm
jarbas/frontend/elm/Format/Date/I18n/I_pt_br.elm
jarbas/frontend/elm/Internationalization.elm
jarbas/frontend/tests/elm-package.json

Fix Elm dates

---

jarbas/frontend/elm/Documents/Decoder.elm
jarbas/frontend/elm/Documents/Model.elm
jarbas/frontend/elm/Documents/View.elm

Fix null term id loading error

---

jarbas/frontend/elm/Documents/Company/View.elm

Add city/state to the top of the company panel

---

jarbas/frontend/elm/Documents/RelatedTable/Model.elm
jarbas/frontend/elm/Documents/RelatedTable/Update.elm
jarbas/frontend/elm/Documents/Update.elm

Example (with current reimbursement repeated in the _same subquota_ panel): https://jarbas.datasciencebr.com/#/documentId/5893871

Remove the current reimbursement from the same subquota panel

---

README.md

In a talk with @cuducos installing the docker version of the app, some fixes needed to be made.

Fix README.md file to docker

---

README.md
contrib/nginx
jarbas/frontend/elm/Layout.elm

Change hardcoded domains to `serenatadeamor.org`

datasciencebr.com -> serenatadeamor.org

---

jarbas/frontend/templates/frontend/home.html

- Add `meta` viewport to improve responsive version
- Remove unnecessary attributes from `script` and `link` tag

Minor template improvements

---

README.md
jarbas/api/tests/test_reimbursement_view.py
jarbas/api/views.py
jarbas/core/querysets.py
jarbas/core/tests/test_reimbursement_model.py

Add suspicions filter to the API

---

README.md

After merging #163 I felt like reorganizing the documentation a bit.
Basically moved stuff around to keep Docker instructions altogether. Also gave more importance to the documentation os the settings.

Update docs (after Docker)

---

jarbas/frontend/elm/Layout.elm

http://serenata.serenatadeamor.org/ -> https://serenatadeamor.org

Fix url from navigation bar

---

README.md

Add Node.js to the docs

---

jarbas/dashboard/admin.py

New dashboard filters: month and document type

---

requirements.txt

fix #233 thanks to @luanfonceca ❤

Reprint 0.4.0 breaks our code. Getting back to version 0.3.0

---

jarbas/core/management/commands/companies.py

Use tuple instead of generator for company keys

---

jarbas/core/management/commands/companies.py
jarbas/core/management/commands/reimbursements.py
jarbas/core/management/commands/suspicions.py

Specifying file encoding

---

requirements.txt

https://docs.djangoproject.com/en/1.11/releases/1.11.5/

Django security update

---

README.md

Added documentation for issue #279.

Added documentation for search vector.

---

Dockerfile
README.md
docker-compose.override.yml
docker-compose.prod.yml
docker-compose.yml
goss.yaml

- Add HEALTHCHECK to dockerfile using goss to validate
See https://medium.com/@aelsabbahy/docker-1-12-kubernetes-simplified-health-checks-and-container-ordering-with-goss-fa8debbe676c
- Add entrypoint to dockerfile
- Fix documentation accordingly
Change docker-compose.yml django from image to build: .
```console
sed -i "s\image: datasciencebr/jarbas-backend\build: .\g" docker-compose.yml
docker-compose build django
docker-compose run --rm django test
docker-compose run --rm django check
docker inspect -f '{{ range .State.Health.Log }}{{ println "======\nStart:" .Start }}{{ .Output }}{{end}}' jarbas_django_1
```
@anaschwendler please could review?

Refactor jarbas-backend docker image

---

docker-compose.prod.yml

Issue #301
Check if Jarbas performance improved
@cuducos

Add config random_page_count for production

---

contrib/.env.sample
jarbas/wsgi.py
requirements.txt

Requires these new environment variables:
```
NEW_RELIC_APP_NAME=Jarbas
NEW_RELIC_ENVIRONMENT=production
NEW_RELIC_LICENSE_KEY=xxx
```

Use NewRelic in Django project

---

README.md

Added New Relic environment variables to README.md

---

README.md
elm-package.json
jarbas/layers/elm/Layout.elm
package.json

Update the source base to reflect the change to the Open Knowledge Foundation account.
Every GitHub address pointing to `datasciencebr` was change by `okfn-brasil`.
Click links, check badges etc.
@anaschwendler @jtemporal @Irio

Change: datasciencebr -> okfn-brasil
